package com.aracroproducts.attention
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF004af1)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFdce1ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001356)
val md_theme_light_secondary = Color(0xFFa700b0)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffd6fa)
val md_theme_light_onSecondaryContainer = Color(0xFF37003b)
val md_theme_light_tertiary = Color(0xFF8d27c5)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFf7d9ff)
val md_theme_light_onTertiaryContainer = Color(0xFF30004c)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfefbff)
val md_theme_light_onBackground = Color(0xFF1b1b1f)
val md_theme_light_surface = Color(0xFFfefbff)
val md_theme_light_onSurface = Color(0xFF1b1b1f)
val md_theme_light_surfaceVariant = Color(0xFFe2e1ec)
val md_theme_light_onSurfaceVariant = Color(0xFF45464f)
val md_theme_light_outline = Color(0xFF76767f)
val md_theme_light_inverseOnSurface = Color(0xFFf3f0f5)
val md_theme_light_inverseSurface = Color(0xFF303034)

val md_theme_dark_primary = Color(0xFFb6c4ff)
val md_theme_dark_onPrimary = Color(0xFF002487)
val md_theme_dark_primaryContainer = Color(0xFF0036bd)
val md_theme_dark_onPrimaryContainer = Color(0xFFdce1ff)
val md_theme_dark_secondary = Color(0xFFffa9fb)
val md_theme_dark_onSecondary = Color(0xFF5a0060)
val md_theme_dark_secondaryContainer = Color(0xFF7f0087)
val md_theme_dark_onSecondaryContainer = Color(0xFFffd6fa)
val md_theme_dark_tertiary = Color(0xFFe8b3ff)
val md_theme_dark_onTertiary = Color(0xFF4f0078)
val md_theme_dark_tertiaryContainer = Color(0xFF7000a8)
val md_theme_dark_onTertiaryContainer = Color(0xFFf7d9ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1b1b1f)
val md_theme_dark_onBackground = Color(0xFFe4e1e6)
val md_theme_dark_surface = Color(0xFF1b1b1f)
val md_theme_dark_onSurface = Color(0xFFe4e1e6)
val md_theme_dark_surfaceVariant = Color(0xFF45464f)
val md_theme_dark_onSurfaceVariant = Color(0xFFc6c5cf)
val md_theme_dark_outline = Color(0xFF909099)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1b1f)
val md_theme_dark_inverseSurface = Color(0xFFe4e1e6)

val seed = Color(0xFF245bff)
val error = Color(0xFFba1b1b)